server:
  port: 8000

spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication-spring
    username: postgres
    password: shetu2153

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret_key: this-is-a-secret-key
